# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='addr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='qq',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
