# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0002_auto_20171105_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='score',
        ),
    ]
