# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
