# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0005_auto_20171105_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
