# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0006_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qq', models.CharField(blank=True, max_length=10)),
                ('addr', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
