# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0007_author1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author1',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
