# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_article', '0009_remove_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_article.Category'),
            preserve_default=False,
        ),
    ]
